config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"

  get "/users", to: "users#index"

  get "/users/:id", to: "users#show", as: "user"

  get "/users/:user_id/posts/new", to: "posts#new", as: "new_user_post"
  post "/users/:user_id/posts", to: "posts#create", as: "posts"

  get "/users/:user_id/posts/:post_id/comments/new", to: "comments#new", as: "new_user_post_comment"
  post "/users/:user_id/posts/:post_id/comments", to: "comments#create", as: "user_post_comments"
  delete "/users/:user_id/posts/:post_id/comments/:comment_id", to: "comments#destroy", as: "delete_comment"

  post "/users/:user_id/posts/:post_id/likes", to: "likes#create", as: "user_post_likes"

  get "/users/:user_id/posts", to: "posts#index", as: "user_posts"

  get "/users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  delete "/users/:user_id/posts/:id", to: "posts#destroy", as: "delete_post"

  namespace :api do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :liked_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_user_posts_counter

  private

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def index
      user = User.find(params[:user_id])
      posts = user.posts

      render json: posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = User.includes(:posts, :comments).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params.merge(liked_counter: 0, comments_counter: 0))
    if @post.save
      redirect_to user_post_path(@post.author, @post)
    else
      flash.now[:alert] = 'Post creation failed!'
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to user_posts_path(@post.author), notice: 'Post deleted successfully.'
    else
      flash[:alert] = 'You are not authorized to delete that post.'
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :liked_counter, :comments_counter)
  end
end

app/views/posts/index.html.erb
<div class="my-3 d-flex justify-content-around align-items-center flex-wrap gap-2">
  <a href="/users/<%= @user.id %>">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" class="img-fluid rounded-start"
      style="width: 100px; height: 100px;">
  </a>

  <h2 class="fw-bold">
    <%= @user.name %>
  </h2>

  <button type="button" class="btn btn-primary align-self-end">
    Number of posts:
    <span class="badge bg-secondary">
      <%= @user.posts_counter ? @user.posts_counter : 0 %>
    </span>
  </button>
</div>


<ul class="list-group mt-5">
  <% @user.posts.each do |post| %>
    <li class="list-group-item my-3 border-top">
      <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="text-reset text-decoration-none">
        <div class="d-flex flex-column gap-2">
          <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="text-reset text-decoration-none">

            <h4 class="fw-bold">
              <%= post.title %>
            </h4>
          </a>
          <p>
            <%= post.text %>
          </p>
          <div class="d-flex justify-content-end">
            <button type="button" class="btn btn-primary me-2">
              Comments:
              <span class="badge bg-secondary">
                <%= post.comments_counter ? post.comments_counter : 0 %>
              </span>
            </button>
            <button type="button" class="btn btn-primary">
              Likes:
              <span class="badge bg-secondary">
                <%= post.liked_counter ? post.liked_counter : 0 %>
              </span>
            </button>
          </div>
          <h4 class="fw-bold"> Comments </h4>
          <ul class="list-group">
            <% if post.comments.length> 0 %>
              <% post.recent_comments.each do |comment| %>
                <li class="list-group-item">
                  <%= comment.author.name %>: <%= comment.text %>
                </li>
                <% end %>
                  <% else %>
                    <li class="list-group-item">No comments</li>
                    <% end %>
          </ul>
        </div>
      </a>
    </li>
    <% end %>
</ul>
<button class="btn btn-primary">Pagination</button>

app/views/posts/new.html.erb
<section class="text-light mt-5">

    <h2 class="mb-4">Create New Post</h2>

    <%= form_with model: @post do |form| %>

        <div class="mb-3">
            <% form.label :title %>
                <%= form.text_field :title, class:"form-control", placeholder:"Enter the Title of the Post" %>
        </div>

        <div class="mb-3">
            <% form.label :text %>
                <%= form.text_field :text, class:"form-control", placeholder:"Enter the Text of the Post" %>
        </div>

        <div>
            <%= form.submit class:'btn btn-primary' %>
        </div>

        <% end %>
</section>

app/views/posts/show.html.erb
<div class="my-3 border border-primary rounded p-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="fw-bold mb-0">
            <%= @post.title %> by <a href="/users/<%= @post.author.id %>">
                <%= @post.author.name %>
            </a>
        </h2>
        <div>
            <button type="button" class="btn btn-primary me-2">
                <i class="fas fa-comment"></i> Comments:
                <span class="badge bg-light text-dark">
                    <%= @post.comments_counter ? @post.comments_counter : 0 %>
                </span>
            </button>
            <%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" do |form| %>
                <%= form.submit "Like", class: "btn btn-primary mt-2" %>
                <span class="badge bg-secondary p-2">
                    <%= @post.liked_counter ? @post.liked_counter : 0 %>
                </span>
            <% end %>
        </div>
    </div>

    <p class="mb-4">
        <%= @post.text %>
    </p>

    <div>
        <h4 class="fw-bold mb-3">Comments</h4>

        <ul class="list-group">
            <% if @post.comments.length > 0 %>
                <% @post.comments.each do |comment| %>
                    <li class="list-group-item py-2">
                        <span class="fw-bold">
                            <%= comment.author.name %>:
                        </span>
                        <%= comment.text %>
                        <% if can?(:destroy, comment) %>
                            <%= form_tag delete_comment_path(@post.author, @post, comment), method: :delete do %>
                                <%= button_tag 'Delete Comment', type: :submit, class: 'btn btn-danger btn-sm float-end' %>
                            <% end %>
                        <% end %>
                    </li>
                <% end %>
            <% else %>
                <li class="list-group-item">No comments</li>
            <% end %>
        </ul>
    </div>

    <div class="mt-5">
        <h4 class="mb-3">Add Comment</h4>
        <%= form_with(model: [@post.author, @post.author.comments.build],
            url: "/users/#{@post.author.id}/posts/#{@post.id}/comments") do |form| %>

            <div class="mb-3">
                <%= form.text_field :text, class: "form-control", placeholder: "Type a comment" %>
            </div>

            <div>
                <%= form.submit class: "btn btn-primary" %>
            </div>

        <% end %>
    </div>

    <% if can?(:destroy, @post) %>
        <div class="float-end">
            <%= form_tag delete_post_path(@post.author, @post), method: :delete do %>
                <%= button_tag 'Delete Post', type: :submit, class: 'btn btn-danger btn-lg' %>
            <% end %>
        </div>
    <% end %>
</div>